# Generated by Django 3.1.2 on 2020-10-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_squashed_0010_auto_20200528_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='link'),
        ),
    ]
