# Generated by Django 3.0.5 on 2020-04-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_squashed_0007_auto_20200427_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
