# Generated by Django 3.0.5 on 2020-04-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20200427_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
