# Generated by Django 3.1.2 on 2020-10-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('agenda', '0002_sponsor_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='default_featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='default featured image'),
        ),
    ]
