# Generated by Django 3.1.2 on 2020-11-20 13:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_edition_default_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_speaker',
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_speakers', to='agenda.event')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.speaker', verbose_name='speaker')),
            ],
            options={
                'verbose_name': 'event speaker',
                'verbose_name_plural': 'event speakers',
            },
        ),
    ]
