# Generated by Django 3.1.2 on 2020-11-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20201120_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspeaker',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_speakers', to='agenda.speaker', verbose_name='speaker'),
        ),
    ]
