# Generated by Django 3.0.5 on 2020-04-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20200428_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='number',
        ),
    ]
