# Generated by Django 3.0.5 on 2020-04-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20200427_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='', upload_to='', verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
