# Generated by Django 3.1.2 on 2020-11-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20201120_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='recording',
            new_name='recording_link',
        ),
    ]
