# Generated by Django 3.0.5 on 2020-05-04 18:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20200429_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='content_pl',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
