# Generated by Django 3.1.4 on 2021-01-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20201227_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(blank=True, choices=[('pl', 'Polish'), ('en', 'English'), ('pl+en', 'Polish+English')], max_length=5, null=True, verbose_name='language'),
        ),
    ]
