# Generated by Django 3.0.6 on 2020-05-28 14:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('agenda', '0009_auto_20200526_2322_squashed_0021_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'event category', 'verbose_name_plural': 'event categories'},
        ),
        migrations.AlterModelOptions(
            name='edition',
            options={'verbose_name': 'edition', 'verbose_name_plural': 'editions'},
        ),
        migrations.AlterModelOptions(
            name='editionindex',
            options={'verbose_name': 'edition index', 'verbose_name_plural': 'edition indexes'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='eventindex',
            options={'verbose_name': 'event list', 'verbose_name_plural': 'event lists'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'speaker', 'verbose_name_plural': 'speakers'},
        ),
        migrations.AlterModelOptions(
            name='speakerindex',
            options={'verbose_name': 'speakers index', 'verbose_name_plural': 'speakers indexes'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'sponsor', 'verbose_name_plural': 'sponsors'},
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#23211f', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be in hex', regex='^#([0-9a-fA-F]{6})$')], verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='category',
            name='edition',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='agenda.Edition', verbose_name='edition'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=300, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='edition end date'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='edition start date'),
        ),
        migrations.AlterField(
            model_name='editionindex',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=wagtail.core.fields.RichTextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_en',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_pl',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='duration in minutes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.Speaker', verbose_name='speaker'),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(blank=True, choices=[('pl', 'Polish'), ('en', 'English')], max_length=5, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recording',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='link to recording'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.Sponsor', verbose_name='sponsor'),
        ),
        migrations.AlterField(
            model_name='eventindex',
            name='color',
            field=models.CharField(default='#23211f', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be in hex', regex='^#([0-9a-fA-F]{6})$')], verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='eventindex',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(max_length=512, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('github', 'Github'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('email', 'Email'), ('site', 'Website'), ('other', 'Other')], default='other', max_length=16, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='content',
            field=wagtail.core.fields.RichTextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='content_en',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='content_pl',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.Sponsor', verbose_name='sponsor'),
        ),
        migrations.AlterField(
            model_name='speakerindex',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
