# Generated by Django 3.0.5 on 2020-05-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_event_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recording',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
