# Generated by Django 3.0.5 on 2020-05-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('agenda', '0011_event_recording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryIndex',
        ),
    ]
