# Generated by Django 3.1.7 on 2021-02-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_audiofile'),
        ('agenda', '0012_auto_20210226_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audio_recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.audiofile', verbose_name='audio recording file'),
        ),
    ]
