# Generated by Django 3.0.5 on 2020-05-26 22:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_auto_20200527_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_pl', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(max_length=300)),
                ('color', models.CharField(default='#23211f', max_length=7, validators=[django.core.validators.RegexValidator(message='Username must be Alphanumeric', regex='^#([0-9a-fA-F]{6})$')], verbose_name='Category color')),
                ('edition', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='agenda.Edition')),
            ],
        ),
    ]
