# Generated by Django 3.1.7 on 2021-02-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_event_audio_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='generate_podcast_feed',
            field=models.BooleanField(default=False, verbose_name='generate podcast feed'),
        ),
    ]
