# Generated by Django 3.0.5 on 2020-05-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_auto_20200527_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
