# Generated by Django 3.1.8 on 2021-04-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('agenda', '0016_auto_20210406_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='', max_length=100, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
