# Generated by Django 3.0.5 on 2020-05-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_auto_20200527_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[('pl', 'Polish'), ('en', 'English')], default='pl', max_length=5),
            preserve_default=False,
        ),
    ]
