# Generated by Django 3.0.5 on 2020-05-27 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_event_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Event category', 'verbose_name_plural': 'Event categories'},
        ),
        migrations.AlterModelOptions(
            name='edition',
            options={'verbose_name': 'Edition', 'verbose_name_plural': 'Editions'},
        ),
        migrations.AlterModelOptions(
            name='editionindex',
            options={'verbose_name': 'Edition index', 'verbose_name_plural': 'Edition indexes'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventindex',
            options={'verbose_name': 'Event list', 'verbose_name_plural': 'Event lists'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'Speaker', 'verbose_name_plural': 'Speakers'},
        ),
        migrations.AlterModelOptions(
            name='speakerindex',
            options={'verbose_name': 'Speakers index', 'verbose_name_plural': 'Speakers indexes'},
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#23211f', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be in hex', regex='^#([0-9a-fA-F]{6})$')], verbose_name='Category color'),
        ),
    ]
