# Generated by Django 3.0.5 on 2020-05-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_auto_20200527_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.Speaker'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(blank=True, choices=[('pl', 'Polish'), ('en', 'English')], max_length=5, null=True),
        ),
    ]
