# Generated by Django 3.0.5 on 2020-05-27 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_auto_20200527_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindex',
            name='color',
            field=models.CharField(default='#23211f', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be in hex', regex='^#([0-9a-fA-F]{6})$')], verbose_name='Index color'),
        ),
    ]
