# Generated by Django 3.0.5 on 2020-05-27 12:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_eventindex_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('github', 'Github'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('email', 'Email'), ('site', 'Website'), ('other', 'Other')], default='other', max_length=16)),
                ('link', models.URLField(max_length=512)),
                ('speaker', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='agenda.Speaker')),
            ],
        ),
    ]
