# Generated by Django 3.1.2 on 2020-10-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201011_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenuentry',
            name='link_title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='link title'),
        ),
        migrations.AddField(
            model_name='navigationmenuentry',
            name='link_title_pl',
            field=models.CharField(max_length=128, null=True, verbose_name='link title'),
        ),
    ]
