# Generated by Django 3.1.2 on 2020-10-11 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('common', '0003_auto_20201012_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenuentry',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Overrides the url field', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='linked page'),
        ),
        migrations.AlterField(
            model_name='navigationmenuentry',
            name='link_url',
            field=models.CharField(blank=True, help_text='Overridden by linked page', max_length=500, null=True, verbose_name='link url'),
        ),
    ]
