# Generated by Django 3.1.4 on 2020-12-12 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('common', '0006_themesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='default_edition_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='default edition image'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='default_footer_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='default footer image'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='slider_primary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='default primary image'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='slider_secondary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='default secondary image'),
        ),
    ]
