# Generated by Django 3.1.7 on 2021-02-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20201212_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='recording file')),
                ('mime_type', models.CharField(blank=True, max_length=64, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'audio recording',
                'verbose_name_plural': 'audio recording',
            },
        ),
    ]
