# Generated by Django 3.1.7 on 2021-02-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='guid_override',
            field=models.CharField(blank=True, help_text='leave empty unless you know what you are doing', max_length=200, null=True, verbose_name='override global unique id'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='duration_seconds',
            field=models.IntegerField(blank=True, help_text='should be detected automatically', null=True, verbose_name='duration in seconds'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='mime_type',
            field=models.CharField(blank=True, help_text='should be detected automatically', max_length=64, null=True, verbose_name='mime type'),
        ),
    ]
