# Generated by Django 3.1.7 on 2021-02-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20210227_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='explicit_content',
            field=models.BooleanField(default=False, verbose_name='explicit content'),
        ),
    ]
