# Generated by Django 3.1.7 on 2021-02-27 23:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('blog', '0002_auto_20200528_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='redirect_to',
            field=models.ForeignKey(blank=True, help_text='Redirect to a specified page instead of showing content. You should still add content or description to show in previews.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.page', verbose_name='redirect to page'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='post date'),
        ),
    ]
