# Generated by Django 3.0.5 on 2020-04-19 11:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_pl',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
